"""Coffee menu terms used by the demo app and the NER dataset builder."""

COFFEE_MENU = [
    "Americano",
    "Cappuccino",
    "Latte",
    "Vanilla Latte",
    "Caramel Macchiato",
    "Flat White",
    "Mocha",
    "Espresso",
    "Cold Brew",
    "Iced Latte",
    "Matcha Latte",
    "Dirty Coffee",
    "Affogato",
    "Piccolo",
    "Cortado",
    "Pour Over",
    "Long Black",
    "Nitro Cold Brew",
    "Hazelnut Latte",
    "Oat Milk Latte",
]

COFFEE_ALIASES = {
    "americano": "Americano",
    "cappuccino": "Cappuccino",
    "latte": "Latte",
    "vanilla latte": "Vanilla Latte",
    "caramel macchiato": "Caramel Macchiato",
    "flat white": "Flat White",
    "mocha": "Mocha",
    "espresso": "Espresso",
    "cold brew": "Cold Brew",
    "iced latte": "Iced Latte",
    "matcha latte": "Matcha Latte",
    "dirty coffee": "Dirty Coffee",
    "affogato": "Affogato",
    "piccolo": "Piccolo",
    "cortado": "Cortado",
    "pour over": "Pour Over",
    "long black": "Long Black",
    "nitro cold brew": "Nitro Cold Brew",
    "hazelnut latte": "Hazelnut Latte",
    "oat milk latte": "Oat Milk Latte",
}

